# Generated by Django 3.2 on 2021-04-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('items_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_code', models.IntegerField(blank=True, null=True)),
                ('items_name', models.CharField(max_length=100)),
            ],
        ),
    ]
