# Generated by Django 3.2 on 2021-04-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_code', models.IntegerField(blank=True, null=True)),
                ('storage_name', models.CharField(max_length=100)),
                ('storage_location', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_code', models.IntegerField(blank=True, null=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_mobile', models.CharField(max_length=100)),
            ],
        ),
    ]
