# Generated by Django 3.2 on 2021-04-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setup', '0004_alter_items_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='items_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
