# Generated by Django 3.2 on 2021-04-26 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Setup', '0004_alter_items_items_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_in',
            fields=[
                ('detail_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_in_code', models.IntegerField(blank=True, null=True)),
                ('detail_in_quantity', models.IntegerField(blank=True, null=True)),
                ('detail_in_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='detail_out',
            fields=[
                ('detail_out_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_out_code', models.IntegerField(blank=True, null=True)),
                ('detail_out_quantity', models.IntegerField(blank=True, null=True)),
                ('detail_out_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='master_out',
            fields=[
                ('master_out_id', models.AutoField(primary_key=True, serialize=False)),
                ('master_out_code', models.IntegerField(blank=True, null=True)),
                ('master_out_date', models.DateField(auto_now_add=True)),
                ('master_out_movenumber', models.IntegerField(blank=True, null=True)),
                ('master_out_notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='master_in',
            fields=[
                ('master_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('master_in_code', models.IntegerField(blank=True, null=True)),
                ('master_in_date', models.DateField(auto_now_add=True)),
                ('master_in_movenumber', models.IntegerField(blank=True, null=True)),
                ('master_in_notes', models.CharField(max_length=1000)),
                ('Supplier_Supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Setup.supplier')),
            ],
        ),
    ]
