# Generated by Django 3.2 on 2021-04-26 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Setup', '0004_alter_items_items_name'),
        ('Transaction', '0002_auto_20210426_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_in',
            name='Customer_Customer_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Setup.customer'),
        ),
        migrations.AlterField(
            model_name='master_in',
            name='Storage_Storage_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Setup.storage'),
        ),
        migrations.AlterField(
            model_name='master_in',
            name='Supplier_Supplier_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Setup.supplier'),
        ),
    ]
