# Generated by Django 3.2 on 2021-04-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_auto_20210427_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_in',
            old_name='Items_Items_id',
            new_name='Items_id',
        ),
        migrations.RenameField(
            model_name='detail_in',
            old_name='Master_in_master_in_id',
            new_name='Master_in_id',
        ),
        migrations.RenameField(
            model_name='detail_out',
            old_name='Items_Items_id',
            new_name='Items_id',
        ),
        migrations.RenameField(
            model_name='detail_out',
            old_name='Master_out_master_out_id',
            new_name='Master_out_id',
        ),
        migrations.RenameField(
            model_name='master_in',
            old_name='Customer_Customer_id',
            new_name='Customer_id',
        ),
        migrations.RenameField(
            model_name='master_in',
            old_name='Storage_Storage_id',
            new_name='Storage_id',
        ),
        migrations.RenameField(
            model_name='master_in',
            old_name='Supplier_Supplier_id',
            new_name='Supplier_id',
        ),
        migrations.RenameField(
            model_name='master_out',
            old_name='Customer_Customer_id',
            new_name='Customer_id',
        ),
        migrations.RenameField(
            model_name='master_out',
            old_name='Storage_Storage_id',
            new_name='Storage_id',
        ),
        migrations.RenameField(
            model_name='master_out',
            old_name='Supplier_Supplier_id',
            new_name='Supplier_id',
        ),
    ]
